version: '3.9'

services:
  doppler.files:
    image: ${DOCKER_REGISTRY-}${DOCKER_NAMESPACE:-dopplerdock}/doppler-files:${VERSION:-latest}
    build:
      context: .
      dockerfile: Doppler.Files.Api/Dockerfile
      target: ${DOCKER_BUILD_TARGET:-final}
      args: 
        version: ${DOCKER_REGISTRY-}${DOCKER_NAMESPACE:-dopplerdock}/doppler-files:${SOURCE_VERSION}